spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oauth2-database
    password: postgres
    username: postgres
  liquibase:
    change-log: classpath:config/liquibase/master.xml
  main:
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      client:
        config:
          login-client:
            connect-timeout: 20000
            read-timeout: 20000
  security:
    oauth2:
      client:
        registration:
          oauth-web-client:
            client-id: application-client
            client-secret: secret
            client-name: application-client
            client-authentication-method: client_secret_post
        provider:
          oauth-web-client:
            authorization-uri: http://localhost:8081/v1/oauth2/authorize
            issuer-uri: http://localhost:8081
            token-uri: http://localhost:8081/v1/oauth2/token
            user-info-uri: http://localhost:8081/v1/oauth2/userinfo
            jwk-set-uri: http://localhost:8081/v1/oauth2/jwks

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.security: TRACE
    jakarta.activation: INFO
    org.ylplabs.usersservice: DEBUG

